-- Session #1
begin
SET SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT * FROM PIZZERIA WHERE NAME LIKE 'Pizza Hut%';
UPDATE PIZZERIA SET RATING = 4 WHERE NAME LIKE 'Pizza Hut';
COMMIT;
SELECT * FROM PIZZERIA WHERE NAME LIKE 'Pizza Hut%';

--Session #2
begin
SET SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT * FROM PIZZERIA WHERE NAME LIKE 'Pizza Hut%';
UPDATE PIZZERIA SET RATING = 3.6 WHERE NAME LIKE 'Pizza Hut';
COMMIT;
SELECT * FROM PIZZERIA WHERE NAME LIKE 'Pizza Hut%';